#!/bin/bash

PARAMS=$1
nmap $PARAMS target.ip -oN nmap.ports
PORTS=$(cat nmap.ports | grep 'open\|closed\|filtered\|unfiltered\|open|filtered\|closed|filtered' | awk '{ print ($0+0 "," $3)}' | sed -z 's/\n/;/g;s/;$/\n/')


oIFS="$IFS"
while IFS=';' read -ra PORT; do
  for i in "${PORT[@]}"; do
    IFS=','
    read -a strarr <<< "$i"
    nmap -sV -sC -p ${strarr[0]} -oN port.${strarr[0]}.${strarr[1]} target.ip
  done
done <<< "$PORTS"

mkdir -p nmap.vulns
while IFS=';' read -ra PORT; do
  for i in "${PORT[@]}"; do
    IFS=','
    read -a strarr <<< "$i"
    nmap -vv --script vuln -p ${strarr[0]} -oN nmap.vulns/port.${strarr[0]}.${strarr[1]}.vuln target.ip
  done
done <<< "$PORTS"

IFS="$oIFS"
unset oIFS
